export const SWAGGER_API_TAG = '1.0';
export const SWAGGER_API_NAME = 'SEEDZ_PAYMENT_CHECKOUT';
export const SWAGGER_API_DESCRIPTION =
  'API IMPLEMENTADA PARA A REALIZAÇÃO DO TESTE TÉCNICO DA SEEDZ';
